version: '3.9'
services:

  java_app:
    container_name: java_app
    image: crud-spring:1.0.0
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - 8090:8090
    environment:
      - DATABASE_URL=jdbc:mysql://mysql_db:3306/crud
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=12345
    depends_on:
      - mysql_db

  mysql_db:
    container_name: mysql_db
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: crud
    volumes:
# ruta donde esta el script sql :/
      - ./data.sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  DB_adminer:
      container_name: DB_adminer
      image: adminer
      restart: unless-stopped
      depends_on:
          - mysql_db
      ports:
          - 8081:8080
      environment:
          ADMINER_DEFAULT_SERVER: mysql_db
        # network_mode: "host"

